services:
  quasar:
    container_name: dac-ui
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - dac_dac
    ports:
      - "9000:80"
    expose:
      - "5113"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
networks:
  dac_dac:
    name: dacodac_dac_dac
    external: true